### ISSUE TITLE
Redis connection problem can crash charles

### ISSUE THREAD

**Issue by juhoojala** [lucified/minard-backend#173]
charles crashed after pushing code to charles, with the following found in logs:

```
sha or branch name master, 3574f77f1809e54a203a11a3a8fcc3eb3023e473
    at Eventstore.getLastEventAsStream (/code/node_modules/eventstore/lib/eventstore.js:506:16)
    at handle_offline_command (/code/node_modules/redis/index.js:846:15)
    at RedisClient.internal_send_command (/code/node_modules/redis/index.js:880:9)
    at RedisClient.scan (/code/node_modules/redis/lib/commands.js:62:25)
    at scanRecursive (/code/node_modules/eventstore/lib/databases/redis.js:285:19)
    at Redis.scan (/code/node_modules/eventstore/lib/databases/redis.js:309:7)
    at Redis.getLastEvent (/code/node_modules/eventstore/lib/databases/redis.js:469:10)
2017-04-03T08:22:16.805Z - error: Unable to post event AbortError: SCAN can't be processed. The connection is already closed.
    at /code/dist/shared/promisify.js:23:22
    at Eventstore.getLastEventAsStream (/code/dist/shared/promisify.js:14:16)
    at PersistentEventBus.<anonymous> (/code/dist/event-bus/persistent-event-bus.js:88:54)
    at Generator.next (<anonymous>)
    at /code/dist/event-bus/persistent-event-bus.js:19:71
    at __awaiter (/code/dist/event-bus/persistent-event-bus.js:15:12)
    at PersistentEventBus._post (/code/dist/event-bus/persistent-event-bus.js:82:16)
    at Object.execute (/code/dist/event-bus/persistent-event-bus.js:79:60)
    at MergeMapSubscriber.stream.prependInit.flatMap.job [as project] (/code/dist/event-bus/persistent-event-bus.js:70:69)
    at MergeMapSubscriber._tryNext (/code/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:120:27)
    at MergeMapSubscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:110:18)
    at MergeMapSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (/code/node_modules/@reactivex/rxjs/dist/cjs/OuterSubscriber.js:19:26)
    at InnerSubscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at Subject.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subject.js:55:25)
    at PersistentEventBus.post (/code/dist/event-bus/persistent-event-bus.js:79:19)
    at SafeSubscriber.__tryOrUnsub (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:234:16)
    at SafeSubscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:183:22)
    at Subscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:125:26)
    at Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at CatchSubscriber.Subscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:125:26)
    at CatchSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at MergeMapSubscriber.notifyNext (/code/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:143:30)
    at InnerSubscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at /code/node_modules/@reactivex/rxjs/dist/cjs/util/subscribeToResult.js:36:29
/code/node_modules/@reactivex/rxjs/dist/cjs/util/subscribeToResult.js:42
            root_1.root.setTimeout(function () { throw err; });
                                                 ^
AbortError: SCAN can't be processed. The connection is already closed.
    at handle_offline_command (/code/node_modules/redis/index.js:846:15)
    at RedisClient.internal_send_command (/code/node_modules/redis/index.js:880:9)
    at RedisClient.scan (/code/node_modules/redis/lib/commands.js:62:25)
    at scanRecursive (/code/node_modules/eventstore/lib/databases/redis.js:285:19)
    at Redis.scan (/code/node_modules/eventstore/lib/databases/redis.js:309:7)
    at Redis.getLastEvent (/code/node_modules/eventstore/lib/databases/redis.js:469:10)
    at Eventstore.getLastEventAsStream (/code/node_modules/eventstore/lib/eventstore.js:506:16)
    at /code/dist/shared/promisify.js:23:22
    at Eventstore.getLastEventAsStream (/code/dist/shared/promisify.js:14:16)
    at PersistentEventBus.<anonymous> (/code/dist/event-bus/persistent-event-bus.js:88:54)
    at Generator.next (<anonymous>)
    at /code/dist/event-bus/persistent-event-bus.js:19:71
    at __awaiter (/code/dist/event-bus/persistent-event-bus.js:15:12)
    at PersistentEventBus._post (/code/dist/event-bus/persistent-event-bus.js:82:16)
    at Object.execute (/code/dist/event-bus/persistent-event-bus.js:79:60)
    at MergeMapSubscriber.stream.prependInit.flatMap.job [as project] (/code/dist/event-bus/persistent-event-bus.js:70:69)
    at MergeMapSubscriber._tryNext (/code/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:120:27)
    at MergeMapSubscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:110:18)
    at MergeMapSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (/code/node_modules/@reactivex/rxjs/dist/cjs/OuterSubscriber.js:19:26)
    at InnerSubscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at Subject.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subject.js:55:25)
    at PersistentEventBus.post (/code/dist/event-bus/persistent-event-bus.js:79:19)
    at SafeSubscriber.__tryOrUnsub (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:234:16)
    at SafeSubscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:183:22)
    at Subscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:125:26)
    at Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at CatchSubscriber.Subscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:125:26)
    at CatchSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at MergeMapSubscriber.notifyNext (/code/node_modules/@reactivex/rxjs/dist/cjs/operator/mergeMap.js:143:30)
    at InnerSubscriber._next (/code/node_modules/@reactivex/rxjs/dist/cjs/InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (/code/node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:89:18)
    at /code/node_modules/@reactivex/rxjs/dist/cjs/util/subscribeToResult.js:36:29
```

**Comment by dennari** [comment]
Fixed in #186
