### ISSUE TITLE
Docker crashes on MacOS

### ISSUE THREAD

**Issue by vsaarinen** [lucified/minard-backend#85]
Every now and then the minard-backend Docker image crashes on MacOS. Here's a log of a crash that happened while no actions were being performed in the UI:

```
runner_1         | ERROR: Failed to load config stat /etc/gitlab-runner/config.toml: transport endpoint is not connected  builds=0
postgresql_1     | ERROR:  could not seek to end of file "base/16384/18720": Transport endpoint is not connected
postgresql_1     | STATEMENT:  SELECT "ci_builds".* FROM "ci_builds" INNER JOIN "projects" ON "projects"."id" = "ci_builds"."gl_project_id" AND "projects"."pending_delete" = $1 LEFT JOIN (SELECT "ci_builds"."gl_project_id", count(*) AS running_builds FROM "ci_builds" WHERE "ci_builds"."type" IN ('Ci::Build') AND "ci_builds"."status" = 'running' AND "ci_builds"."runner_id" IN (SELECT "ci_runners"."id" FROM "ci_runners" WHERE "ci_runners"."is_shared" = 't') GROUP BY "ci_builds"."gl_project_id") AS project_builds ON ci_builds.gl_project_id=project_builds.gl_project_id WHERE "ci_builds"."type" IN ('Ci::Build') AND "ci_builds"."status" = $2 AND "ci_builds"."runner_id" IS NULL AND "projects"."builds_enabled" = $3 AND "projects"."shared_runners_enabled" = $4  ORDER BY COALESCE(project_builds.running_builds, 0) ASC, ci_builds.id ASC
runner_1         | WARNING: Checking for builds... failed              runner=da7c8d57 status=500 Internal Server Error
charles_1        | 161010/105805.354, [response] http://0.0.0.0:8000: post /ci/api/v1/builds/register.json {} 500 (413ms)
postgresql_1     | LOG:  received smart shutdown request
redis_1          | [1 | signal handler] (1476097087) Received SIGTERM, scheduling shutdown...
redis_1          | [1] 10 Oct 10:58:07.663 # User requested shutdown...
redis_1          | [1] 10 Oct 10:58:07.664 # Failed opening .rdb for saving: Transport endpoint is not connected
redis_1          | [1] 10 Oct 10:58:07.664 # Error trying to save the DB, can't exit.
redis_1          | [1] 10 Oct 10:58:07.664 # SIGTERM received but errors trying to shut down the server, check the logs for more information
postgresql_1     | LOG:  autovacuum launcher shutting down
Exception in thread Thread-15:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
  File "threading.py", line 763, in run
  File "compose/cli/log_printer.py", line 190, in watch_events
  File "compose/project.py", line 343, in events
  File "site-packages/docker/client.py", line 253, in _stream_helper
  File "json/__init__.py", line 338, in loads
  File "json/decoder.py", line 369, in decode
ValueError: Extra data: line 2 column 1 - line 8 column 1 (char 668 - 4986)

runner_1         | All workers stopped. Can exit now                   builds=0
runner_1         | WARNING: Requested service stop: terminated         builds=0
gitlab_1         | 2016-10-10 16:28:08,058 WARN received SIGTERM indicating exit request
gitlab_1         | 2016-10-10 16:28:08,747 INFO waiting for sshd, gitlab-workhorse, sidekiq, cron, nginx, unicorn to die
gitlab_1         | 2016-10-10 16:28:08,921 INFO stopped: sshd (exit status 0)
gitlab_1         | 2016-10-10 16:28:10,125 INFO stopped: nginx (exit status 0)
gitlab_1         | 2016-10-10 16:28:10,166 INFO stopped: cron (terminated by SIGTERM)
gitlab_1         | 2016-10-10 16:28:10,231 INFO stopped: gitlab-workhorse (exit status 2)
screenshotter_1  | npm info lifecycle screenshotter@0.1.0~poststart: screenshotter@0.1.0
gitlab_1         | 2016-10-10 16:28:12,390 INFO waiting for sidekiq, unicorn to die
screenshotter_1  | npm info ok
gitlab_1         | 2016-10-10 16:28:15,400 INFO waiting for sidekiq, unicorn to die
minardbackend_bind_1 exited with code 0
Exception in thread Thread-13:
Traceback (most recent call last):
  File "threading.py", line 810, in __bootstrap_inner
[...]
```

**Comment by dennari** [comment]
Does this still seem to be an issue?

**Comment by vsaarinen** [comment]
Nope, haven't run into it.
